### ISSUE TITLE
Julkaisu

### ISSUE THREAD

**Issue by hylje** [okffi/decisions#10]
Julkaisu vaatii vielä muutama juttua.
- Pysyvä deployment-alusta. Nykyinen väliaikainen alusta päättyy tämän kuun lopussa. Alustan olisi hyvä pyörittää Dockeria.
- Palvelulle lopullinen nimi. Nykyinen työnimi on "Decisions" tai "Päätökset", joka on aika mitäänsanomaton. Nimen perusteella oma domain-nimi tai subdomain 
- Sähköpostipalvelu, joka sallii lähettää sähköpostia oman domainin nimissä

**Comment by jaakkokorhonen** [comment]
avohoito.okf.fi
Decisions - decisions.okf.fi
Miten toimisi decisions@tietopyynto.fi ?

**Comment by hylje** [comment]
Nyt on toistaiseksi pysyvä julkaisu tehty: [decisions.okf.fi](http://decisions.okf.fi)
