### ISSUE TITLE
Ahjo: Asiasanat

### ISSUE THREAD

**Issue by hylje** [okffi/decisions#16]
Ahjon datassa on kentät issue.category_name, issue.districts ja classification_description joista voisi ottaa asiasanoja irti helposti haettavaan muotoon.

**Comment by jaakkokorhonen** [comment]
CSS tässä, http://d-cent.github.io/patterns/public/patterns/00-atoms-06-buttons-02-tags/00-atoms-06-buttons-02-tags.html
