### ISSUE TITLE
Expand database

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/decisions#21]
searching "pyöräily":
![screenshot 2016-04-11 10 41 01](https://cloud.githubusercontent.com/assets/3482497/14419960/e9bedc6c-ffd1-11e5-9cba-4c2740031e45.png)

**Comment by hylje** [comment]
Latasin sinne jotain 5000 uusinta päätösasiaa. Useimmista kunnalla ylipäätään tapahtuvista asioista pitäisi nyt näkyä edes jotain.

Voikkoa ei ole vielä laitettu tuotantodockeriin joten taivutus voi tuottaa vielä haasteita. 

http://decisions.okf.fi/search/?q=pyöräily
