### ISSUE TITLE
Replace commenting box static size with automatically resizeable text box

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/decisions#23]
So that there will be no scroll bar inside the text box.

![screenshot 2016-04-11 10 43 28](https://cloud.githubusercontent.com/assets/3482497/14420014/401a5276-ffd2-11e5-8190-c57952ade42f.png)

**Comment by hylje** [comment]
Kommenttilaatikko säätää kokoaan tekstimäärän mukaan.
