### ISSUE TITLE
Hakutuloksien palaute

### ISSUE THREAD

**Issue by hylje** [okffi/decisions#29]
- Pitäisi näyttää kuinka paljon tuloksia on, ja aktiivinen hakusana isosti ja selkeästi
- Animoi haun valmistuminen jotenkin, jos palvelu skulaa liian nopeasti

**Comment by jaakkokorhonen** [comment]
icon-spinner löytyy ikoneista

**Comment by jaakkokorhonen** [comment]
Väreissä http://d-cent.github.io/patterns/public/patterns/00-atoms-01-global-00-colors/00-atoms-01-global-00-colors.html on kuvattu "Magenta combinations are for special highlights".
