### ISSUE TITLE
Kommentointi visuaaliseksi

### ISSUE THREAD

**Issue by hylje** [okffi/decisions#30]
- Näytetään selkeästi päätöksiä selattaessa, mihin voi kommentoida. Myös nykyisen kommenttibadgen voi varmaan siirtää tähän.

**Comment by jaakkokorhonen** [comment]
Ei-kommentoitavissa olevat headerit voi olla #666666 subheader colorilla, ja h1 pääheaderivärillä #00444A. Kommentoitavat elementit #222222.
