### ISSUE TITLE
Sisältötiheys mittarikentässä

### ISSUE THREAD

**Issue by hylje** [okffi/decisions#31]
- Jaetaan mittarikenttä yhden asian sivuihin. Säilytetään vaikka nykyinen etusivukenttä ja käytettävät toiminnot omille sivuilleen.

**Comment by jaakkokorhonen** [comment]
Lisätään headeri ja sinne navigoinnit toisille sivuille. Notifikaatioiden määrän esittämiseen löytyy headerissa css.
