### ISSUE TITLE
Uuden tilauksen luominen mittarikentästä/tilauslistasta

### ISSUE THREAD

**Issue by hylje** [okffi/decisions#32]
Uusia tilauksia voisi luoda pikalomakkeella suoraan tilauslistalta. Tämä voi joko olla tavallinen hakupalkki tai suoraan tilauksen luominen.

**Comment by jaakkokorhonen** [comment]
Avainsanasta oletuksena menee tämän avainsanan hakuun, josta pääsee merkitsemään haetun näkymän seurantaan. Joku avainsana voi osoittaa karttahakuun. Myöhemmin voidaan miettiä, miten hakutuloksista saadaan muitakin kuin kartalla olevia ja semanttiseen hakuun vastaavia.
