### ISSUE TITLE
Quicker pull of Ahjo data

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/decisions#79]
Decisions needs to see new data quicker:

http://decisions.okf.fi/search/?q=liikuntalautakunta+talousarvioehdotus+2017

![screen shot 2016-05-12 at 16 35 11](https://cloud.githubusercontent.com/assets/3482497/15216441/b825203e-185f-11e6-9181-580c4c8a114b.png)
![screen shot 2016-05-12 at 16 35 22](https://cloud.githubusercontent.com/assets/3482497/15216442/b8267d6c-185f-11e6-8b85-ddfa6bed176f.png)

**Comment by hylje** [comment]
Capacity allocation issue. I'll have to give more processing power to the background worker, but not too much that the other services on avohoito will suffer.

**Comment by jaakkokorhonen** [comment]
Yeah let's put the connector in a separate docker container to a separate space.

**Comment by hylje** [comment]
Increased the worker's CPU quota somewhat. Let's see if it's fast enough. Also, I'll have to make the code deal with really slow workers better.
